package br.com.anuncios.model;
// Generated 13/03/2012 23:00:23 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;


/**
 * Bairro generated by hbm2java
 */
@Entity
@Table(name="bairro")
public class Bairro  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -6670348854632238974L;
	private Integer idBairro;
     private String descricaoB;
     private String descricao;
     private String idUf;
     private Cidade cidade;

    public Bairro() {
    }

	
    public Bairro(int idBairro) {
        this.idBairro = idBairro;
    }

//    public Bairro(String descricaoB, String descricao, String idUf, int idCidade) {
//       this.descricaoB = descricaoB;
//       this.descricao = descricao;
//       this.idUf = idUf;
//       this.idCidade = idCidade;
//    }
   
    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="idBairro", unique=true, nullable=false)
    public Integer getIdBairro() {
        return this.idBairro;
    }
    
    public void setIdBairro(Integer idBairro) {
        this.idBairro = idBairro;
    }

    
    @Column(name="descricaoB", length=60)
    @Length(max=60)
    public String getDescricaoB() {
        return this.descricaoB;
    }
    
    public void setDescricaoB(String descricaoB) {
        this.descricaoB = descricaoB;
    }

    
    @Column(name="descricao", length=50)
    @Length(max=50)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="idUf", length=2)
    @Length(max=2)
    public String getIdUf() {
        return this.idUf;
    }
    
    public void setIdUf(String idUf) {
        this.idUf = idUf;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCidade", nullable=false)
	public Cidade getCidade() {
		return cidade;
	}


	public void setCidade(Cidade cidade) {
		this.cidade = cidade;
	}

    
//    @Column(name="idCidade", nullable=false)
//    public int getIdCidade() {
//        return this.idCidade;
//    }
//    
//    public void setIdCidade(int idCidade) {
//        this.idCidade = idCidade;
//    }




}


