package br.com.anuncios.model;
// Generated 13/03/2012 23:00:23 by Hibernate Tools 3.4.0.CR1


import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;


/**
 * Cidade generated by hbm2java
 */
@Entity
@Table(name="cidade")
public class Cidade  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -6866222104452139651L;
	private Integer idCidade;
     private Uf uf;
     private Integer cep;
     private String descricao;
     private String descricaoB;
     private Integer locNumSequencialSub;
     private Integer situacao;
     private String tipoLocalidade;
     private List<Bairro> bairros = new ArrayList<Bairro>(0);

    public Cidade() {
    }

	
    public Cidade(Uf uf) {
        this.uf = uf;
    }
    public Cidade(Uf uf, Integer cep, String descicao, String descicaoB, Integer locNumSequencialSub, Integer situacao, String tipoLocalidade) {
       this.uf = uf;
       this.cep = cep;
       this.descricao = descicao;
       this.descricaoB = descicaoB;
       this.locNumSequencialSub = locNumSequencialSub;
       this.situacao = situacao;
       this.tipoLocalidade = tipoLocalidade;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="idCidade", unique=true, nullable=false)
    public Integer getIdCidade() {
        return this.idCidade;
    }
    
    public void setIdCidade(Integer idCidade) {
        this.idCidade = idCidade;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_uf", nullable=false)
    @NotNull
    public Uf getUf() {
        return this.uf;
    }
    
    public void setUf(Uf uf) {
        this.uf = uf;
    }

    
    @Column(name="cep")
    public Integer getCep() {
        return this.cep;
    }
    
    public void setCep(Integer cep) {
        this.cep = cep;
    }

    
    @Column(name="descricao", length=50)
    @Length(max=50)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descicao) {
        this.descricao = descicao;
    }

    
    @Column(name="descricaoB", length=60)
    @Length(max=60)
    public String getDescricaoB() {
        return this.descricaoB;
    }
    
    public void setDescricaoB(String descicaoB) {
        this.descricaoB = descicaoB;
    }

    
    @Column(name="locNumSequencialSub")
    public Integer getLocNumSequencialSub() {
        return this.locNumSequencialSub;
    }
    
    public void setLocNumSequencialSub(Integer locNumSequencialSub) {
        this.locNumSequencialSub = locNumSequencialSub;
    }

    
    @Column(name="situacao")
    public Integer getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(Integer situacao) {
        this.situacao = situacao;
    }

    
    @Column(name="tipoLocalidade", length=1)
    @Length(max=1)
    public String getTipoLocalidade() {
        return this.tipoLocalidade;
    }
    
    public void setTipoLocalidade(String tipoLocalidade) {
        this.tipoLocalidade = tipoLocalidade;
    }


    @OneToMany(fetch=FetchType.LAZY, mappedBy="cidade")
	public List<Bairro> getBairros() {
		return bairros;
	}


	public void setBairros(List<Bairro> bairros) {
		this.bairros = bairros;
	}




}


